name: MarkBanuelos
favicon: null
layout_spectrum: 0.77034
typography_spectrum: 0.74093
title: Mark Banuelos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bfbfbf'
    - '#444444'
    - '#000000'
    - '#6f6f6f'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
